package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "xenture_online_test", uniqueConstraints = @UniqueConstraint(columnNames = "admin_email_id"))
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminEmailId;
	private String adminPassword;
	private Date adminCreatedOn;
	private String adminLogoutTime;
	private Date adminLoginTime;
	private Integer adminAliveStatus;

	public Admin() {
	}

	public Admin(String adminEmailId, String adminPassword, Date adminCreatedOn, String adminLogoutTime,
			Date adminLoginTime, Integer adminAliveStatus) {
		this.adminEmailId = adminEmailId;
		this.adminPassword = adminPassword;
		this.adminCreatedOn = adminCreatedOn;
		this.adminLogoutTime = adminLogoutTime;
		this.adminLoginTime = adminLoginTime;
		this.adminAliveStatus = adminAliveStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "admin_id", unique = true, nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "admin_email_id", unique = true, length = 20)
	public String getAdminEmailId() {
		return this.adminEmailId;
	}

	public void setAdminEmailId(String adminEmailId) {
		this.adminEmailId = adminEmailId;
	}

	@Column(name = "admin_password", length = 20)
	public String getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "admin_created_on", length = 19)
	public Date getAdminCreatedOn() {
		return this.adminCreatedOn;
	}

	public void setAdminCreatedOn(Date adminCreatedOn) {
		this.adminCreatedOn = adminCreatedOn;
	}

	@Column(name = "admin_logout_time", length = 55)
	public String getAdminLogoutTime() {
		return this.adminLogoutTime;
	}

	public void setAdminLogoutTime(String adminLogoutTime) {
		this.adminLogoutTime = adminLogoutTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "admin_login_time", length = 19)
	public Date getAdminLoginTime() {
		return this.adminLoginTime;
	}

	public void setAdminLoginTime(Date adminLoginTime) {
		this.adminLoginTime = adminLoginTime;
	}

	@Column(name = "admin_alive_status")
	public Integer getAdminAliveStatus() {
		return this.adminAliveStatus;
	}

	public void setAdminAliveStatus(Integer adminAliveStatus) {
		this.adminAliveStatus = adminAliveStatus;
	}

}
