package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionCategories generated by hbm2java
 */
@Entity
@Table(name = "question_categories", catalog = "xenture_online_test")
public class Categories implements java.io.Serializable {

	private Integer questionCategoriesId;
	private String categoriesName;
	private int categoriesType;
	private Set<Registration> registrations = new HashSet<Registration>(0);
	private Set<Notification> notifications = new HashSet<Notification>(0);
	private Set<Question> questions = new HashSet<Question>(0);

	public Categories() {
	}

	public Categories(String categoriesName, int categoriesType) {
		this.categoriesName = categoriesName;
		this.categoriesType = categoriesType;
	}

	public Categories(String categoriesName, int categoriesType, Set<Registration> registrations,
			Set<Notification> notifications, Set<Question> questions) {
		this.categoriesName = categoriesName;
		this.categoriesType = categoriesType;
		this.registrations = registrations;
		this.notifications = notifications;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_categories_id", unique = true, nullable = false)
	public Integer getQuestionCategoriesId() {
		return this.questionCategoriesId;
	}

	public void setQuestionCategoriesId(Integer questionCategoriesId) {
		this.questionCategoriesId = questionCategoriesId;
	}

	@Column(name = "categories_name", nullable = false)
	public String getCategoriesName() {
		return this.categoriesName;
	}

	public void setCategoriesName(String categoriesName) {
		this.categoriesName = categoriesName;
	}

	@Column(name = "categories_type", nullable = false)
	public int getCategoriesType() {
		return this.categoriesType;
	}

	public void setCategoriesType(int categoriesType) {
		this.categoriesType = categoriesType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionCategories")
	public Set<Registration> getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set<Registration> registrations) {
		this.registrations = registrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionCategories")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionCategories")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
