package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * College generated by hbm2java
 */
@Entity
@Table(name = "college", catalog = "xenture_online_test")
public class College implements java.io.Serializable {

	private Integer collegeId;
	private String collegeName;
	private String collegeCity;
	private Date collegeCreatedOn;
	private Date collegeUpdatedOn;
	private Set<Registration> registrations = new HashSet<Registration>(0);

	public College() {
	}

	public College(String collegeName, Date collegeCreatedOn) {
		this.collegeName = collegeName;
		this.collegeCreatedOn = collegeCreatedOn;
	}

	public College(String collegeName, String collegeCity, Date collegeCreatedOn, Date collegeUpdatedOn,
			Set<Registration> registrations) {
		this.collegeName = collegeName;
		this.collegeCity = collegeCity;
		this.collegeCreatedOn = collegeCreatedOn;
		this.collegeUpdatedOn = collegeUpdatedOn;
		this.registrations = registrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "college_id", unique = true, nullable = false)
	public Integer getCollegeId() {
		return this.collegeId;
	}

	public void setCollegeId(Integer collegeId) {
		this.collegeId = collegeId;
	}

	@Column(name = "college_name", nullable = false, length = 50)
	public String getCollegeName() {
		return this.collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	@Column(name = "college_city", length = 25)
	public String getCollegeCity() {
		return this.collegeCity;
	}

	public void setCollegeCity(String collegeCity) {
		this.collegeCity = collegeCity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "college_created_on", nullable = false, length = 19)
	public Date getCollegeCreatedOn() {
		return this.collegeCreatedOn;
	}

	public void setCollegeCreatedOn(Date collegeCreatedOn) {
		this.collegeCreatedOn = collegeCreatedOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "college_updated_on", length = 10)
	public Date getCollegeUpdatedOn() {
		return this.collegeUpdatedOn;
	}

	public void setCollegeUpdatedOn(Date collegeUpdatedOn) {
		this.collegeUpdatedOn = collegeUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "college")
	public Set<Registration> getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set<Registration> registrations) {
		this.registrations = registrations;
	}

}
