package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DescriptiveAnswer generated by hbm2java
 */
@Entity
@Table(name = "descriptive_answer", catalog = "xenture_online_test")
public class DescriptiveAnswer implements java.io.Serializable {

	private Integer descAnsId;
	private Question question;
	private Registration registration;
	private String descAnswer;

	public DescriptiveAnswer() {
	}

	public DescriptiveAnswer(Question question, Registration registration, String descAnswer) {
		this.question = question;
		this.registration = registration;
		this.descAnswer = descAnswer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "desc_ans_id", unique = true, nullable = false)
	public Integer getDescAnsId() {
		return this.descAnsId;
	}

	public void setDescAnsId(Integer descAnsId) {
		this.descAnsId = descAnsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ques_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id")
	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	@Column(name = "desc_answer", length = 16777215)
	public String getDescAnswer() {
		return this.descAnswer;
	}

	public void setDescAnswer(String descAnswer) {
		this.descAnswer = descAnswer;
	}

}
