package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "xenture_online_test")
public class Notification implements java.io.Serializable {

	private Integer notifyId;
	private Categories questionCategories;
	private Registration registration;
	private String notification;
	private String createOn;
	private Integer notificationStatus;
	private String notificationTitle;

	public Notification() {
	}

	public Notification(Categories questionCategories, Registration registration, String notification,
			String createOn, Integer notificationStatus, String notificationTitle) {
		this.questionCategories = questionCategories;
		this.registration = registration;
		this.notification = notification;
		this.createOn = createOn;
		this.notificationStatus = notificationStatus;
		this.notificationTitle = notificationTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "notify_id", unique = true, nullable = false)
	public Integer getNotifyId() {
		return this.notifyId;
	}

	public void setNotifyId(Integer notifyId) {
		this.notifyId = notifyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_categories_id")
	public Categories getQuestionCategories() {
		return this.questionCategories;
	}

	public void setQuestionCategories(Categories questionCategories) {
		this.questionCategories = questionCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id")
	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	@Column(name = "notification")
	public String getNotification() {
		return this.notification;
	}

	public void setNotification(String notification) {
		this.notification = notification;
	}

	@Column(name = "create_on")
	public String getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(String createOn) {
		this.createOn = createOn;
	}

	@Column(name = "notification_status")
	public Integer getNotificationStatus() {
		return this.notificationStatus;
	}

	public void setNotificationStatus(Integer notificationStatus) {
		this.notificationStatus = notificationStatus;
	}

	@Column(name = "notification_title")
	public String getNotificationTitle() {
		return this.notificationTitle;
	}

	public void setNotificationTitle(String notificationTitle) {
		this.notificationTitle = notificationTitle;
	}

}
