package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "xenture_online_test")
public class Question implements java.io.Serializable {

	private Integer quesId;
	private Categories questionCategories;
	private String quesQuestion;
	private String questAnsOpt1;
	private String questAnsOpt2;
	private String questAnsOpt3;
	private String questAnsOpt4;
	private String questAnswer;
	private Set<DescriptiveAnswer> descriptiveAnswers = new HashSet<DescriptiveAnswer>(0);

	public Question() {
	}

	public Question(Categories questionCategories, String quesQuestion, String questAnsOpt1,
			String questAnsOpt2, String questAnsOpt3, String questAnsOpt4, String questAnswer,
			Set<DescriptiveAnswer> descriptiveAnswers) {
		this.questionCategories = questionCategories;
		this.quesQuestion = quesQuestion;
		this.questAnsOpt1 = questAnsOpt1;
		this.questAnsOpt2 = questAnsOpt2;
		this.questAnsOpt3 = questAnsOpt3;
		this.questAnsOpt4 = questAnsOpt4;
		this.questAnswer = questAnswer;
		this.descriptiveAnswers = descriptiveAnswers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ques_id", unique = true, nullable = false)
	public Integer getQuesId() {
		return this.quesId;
	}

	public void setQuesId(Integer quesId) {
		this.quesId = quesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_categories_id")
	public Categories getQuestionCategories() {
		return this.questionCategories;
	}

	public void setQuestionCategories(Categories questionCategories) {
		this.questionCategories = questionCategories;
	}

	@Column(name = "ques_question")
	public String getQuesQuestion() {
		return this.quesQuestion;
	}

	public void setQuesQuestion(String quesQuestion) {
		this.quesQuestion = quesQuestion;
	}

	@Column(name = "quest_ans_opt1")
	public String getQuestAnsOpt1() {
		return this.questAnsOpt1;
	}

	public void setQuestAnsOpt1(String questAnsOpt1) {
		this.questAnsOpt1 = questAnsOpt1;
	}

	@Column(name = "quest_ans_opt2")
	public String getQuestAnsOpt2() {
		return this.questAnsOpt2;
	}

	public void setQuestAnsOpt2(String questAnsOpt2) {
		this.questAnsOpt2 = questAnsOpt2;
	}

	@Column(name = "quest_ans_opt3")
	public String getQuestAnsOpt3() {
		return this.questAnsOpt3;
	}

	public void setQuestAnsOpt3(String questAnsOpt3) {
		this.questAnsOpt3 = questAnsOpt3;
	}

	@Column(name = "quest_ans_opt4")
	public String getQuestAnsOpt4() {
		return this.questAnsOpt4;
	}

	public void setQuestAnsOpt4(String questAnsOpt4) {
		this.questAnsOpt4 = questAnsOpt4;
	}

	@Column(name = "quest_answer")
	public String getQuestAnswer() {
		return this.questAnswer;
	}

	public void setQuestAnswer(String questAnswer) {
		this.questAnswer = questAnswer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<DescriptiveAnswer> getDescriptiveAnswers() {
		return this.descriptiveAnswers;
	}

	public void setDescriptiveAnswers(Set<DescriptiveAnswer> descriptiveAnswers) {
		this.descriptiveAnswers = descriptiveAnswers;
	}

}
