package co.xenture.model;
// Generated Mar 7, 2018 12:53:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StateMaster generated by hbm2java
 */
@Entity
@Table(name = "state_master", catalog = "xenture_online_test")
public class StateMaster implements java.io.Serializable {

	private Integer stateId;
	private String stateName;
	private int countryId;
	private Date createdOn;
	private Date lastUpdated;
	private Set<Registration> registrations = new HashSet<Registration>(0);
	private Set<CityMaster> cityMasters = new HashSet<CityMaster>(0);

	public StateMaster() {
	}

	public StateMaster(String stateName, int countryId, Date createdOn, Date lastUpdated) {
		this.stateName = stateName;
		this.countryId = countryId;
		this.createdOn = createdOn;
		this.lastUpdated = lastUpdated;
	}

	public StateMaster(String stateName, int countryId, Date createdOn, Date lastUpdated,
			Set<Registration> registrations, Set<CityMaster> cityMasters) {
		this.stateName = stateName;
		this.countryId = countryId;
		this.createdOn = createdOn;
		this.lastUpdated = lastUpdated;
		this.registrations = registrations;
		this.cityMasters = cityMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "state_id", unique = true, nullable = false)
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "state_name", nullable = false, length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "country_id", nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stateMaster")
	public Set<Registration> getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set<Registration> registrations) {
		this.registrations = registrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stateMaster")
	public Set<CityMaster> getCityMasters() {
		return this.cityMasters;
	}

	public void setCityMasters(Set<CityMaster> cityMasters) {
		this.cityMasters = cityMasters;
	}

}
